include classpath("application.conf")

node-address {
  protocol = http
  host = "0.0.0.0"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

queues {
  article-audio-jobs {
    defaultVisibilityTimeout = 300 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "article-audio-jobs-dlq"
      maxReceiveCount = 3
    }
  }

  article-audio-jobs-dlq {
    defaultVisibilityTimeout = 300 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
  }
}
